name = "Nonagon"
license = "MIT"
licenselink = "https://github.com/gregdhill/nonagon/blob/master/LICENSE"
description = "Homepage & Blog"
homepage = "https://greghill.io"
tags = []
features = []
min_version = ""

[author]
  name = "Gregory Hill"
  homepage = "greghill.io"